[theme]
primaryColor = "#1E90FF"  # Dodger Blue for buttons and highlights
backgroundColor = "#FFFFFF"  # White for the main background
secondaryBackgroundColor = "#B0E0E6"  # Powder Blue for the sidebar
textColor = "#333333"  # Dark Grey for text
font = "sans serif"